### ISSUE TITLE
Log Spam Server

### ISSUE THREAD

**Issue by Mr-Fluuff** [fzzyhmstrs/gc#1]
Server is getting Log Spam from this mod.

![image](https://github.com/fzzyhmstrs/gc/assets/79845185/ef3fae87-9177-4c7d-9e01-450a50641aa0)

**Comment by fzzyhmstrs** [comment]
What version are you running?

**Comment by Mr-Fluuff** [comment]
The latest on fabric. Minecraft version 1.20.1

**Comment by fzzyhmstrs** [comment]
0.3.3+1.20.1? It's impossible for me to know if you truly are using the latest, without just telling me the version number. Because with 0.3.3, I've tested on both a server and singleplayer, with both Imbued Gear included and not included, and do not get log spam.

**Comment by Mr-Fluuff** [comment]
Yes sorry. O.3.3+1.20.1. It spams when someone is connected to the server and has items in their hot bar and then scrolled between the items. Every scroll creates log spam. It does nothing when the player is idle

**Comment by Mr-Fluuff** [comment]
Oh... I do apologize. I just checked with the server owner and she says it's 0.3.2. Will update and see if that solves our problem. Truly am sorry

**Comment by Mr-Fluuff** [comment]
Updating did fix this issue. Truly am sorry for the inconvenience. Keep up the great work
